# Generated by Django 5.1.4 on 2025-01-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
    ]
