# Generated by Django 5.1.4 on 2024-12-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('posts', models.ManyToManyField(related_name='categories', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
